
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const BidDetails = lazy(() => import("./pages/BidDetails.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Documentacao = lazy(() => import("./pages/Documentacao.tsx"));
const ForgotPassword = lazy(() => import("./pages/ForgotPassword.tsx"));
const LicitacaoDetails = lazy(() => import("./pages/LicitacaoDetails.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const NewHomePage = lazy(() => import("./pages/NewHomePage.tsx"));
const ResetPassword = lazy(() => import("./pages/ResetPassword.tsx"));
const SignUp = lazy(() => import("./pages/SignUp.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/bid-details", element: <BidDetails />},
	{ path: "/biddetails", element: <BidDetails />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/documentacao", element: <Documentacao />},
	{ path: "/forgot-password", element: <ForgotPassword />},
	{ path: "/forgotpassword", element: <ForgotPassword />},
	{ path: "/licitacao-details", element: <LicitacaoDetails />},
	{ path: "/licitacaodetails", element: <LicitacaoDetails />},
	{ path: "/login", element: <Login />},
	{ path: "/new-home-page", element: <NewHomePage />},
	{ path: "/newhomepage", element: <NewHomePage />},
	{ path: "/reset-password", element: <ResetPassword />},
	{ path: "/resetpassword", element: <ResetPassword />},
	{ path: "/sign-up", element: <SignUp />},
	{ path: "/signup", element: <SignUp />},

];
